### ISSUE TITLE
Your plugin gives out complete nonsense at the end of the round.

### ISSUE THREAD

**Issue by PUDGE133** [BuildBoy12/EndConditions#2]
Your plugin gives out complete nonsense at the end of the round. The winning teams are those that shouldn't be winning at all. Either I'm dumb or your plugin is shit.
```yaml
#None of the following are case sensative, but it looks good
endconditions:
    # Name of the leading team
    FacilityForces:
        ##Condition name: Literally up to you, can be used as an identifier if you want
        ##The ONLY rule for this is to NOT have two with the same name that are under the same leading team.
        #Append "+science" or "+classd" to the name to check if at least one person has escaped from that team
        #Append "-science" or "-classd" to the name to check if nobody has escaped from that team
        #Note that this can create situations where the round will not end if there is one person alive. Make sure you cover all situations.
        - Default 1:
            #Who wins together, using ClassNames from #resources in the EXILED discord
            - NtfCommander
            - NtfLieutenant
            - NtfCadet
            - NtfScientist
            - FacilityGuard
            - Scientist
            - Tutorial
    ChaosInsurgency:
        - Default 1:
            - ChaosInsurgency
            - ClassD
            - Tutorial
    Anomalies:
        - Default 1:
            - Scp173
            - Scp106
            - Scp049
            - Scp079
            - Scp096
            - Scp0492
            - Scp93953
            - Scp93989
            - Tutorial
    Draw:
        - Default 1:
            - Spectator
            - Tutorial
```
There were 3 players. I used an instant explosion of the warhead. Judging by the logic of this config, the round should have ended in a draw. But for some reason MTF counted the victory.

**Comment by PUDGE133** [comment]
I already imagine that you say: "The Spectator role is not in my plugin." Why the fuck isn't he there? He is in the game, which means his role must be taken into account. Moreover, in this case it is really important. If all the players in the complex died, then why does the MTF count as a victory?

**Comment by BuildBoy12** [comment]
Spectators aren't counted, hence why they aren't there by default. If you add spectators the round would likely never end. The logical reasoning of why mtf would win would be that since you don't have any escape conditions specified and everybody was dead, it would select the first team. Since that team is FacilityForces, they won.

**Comment by PUDGE133** [comment]
I don't quite understand. How it works? Why can't it be done as it would be logical?

**Comment by BuildBoy12** [comment]
If all people were dead, it would meet every possible condition. Since you have no escape conditions, it will always select MTF to win since they are the first condition. The plugin simply iterates through each condition and stops when it finds one that matches the current alive players.

**Comment by PUDGE133** [comment]
But this is complete nonsense. It is not right. What difference does it make who escaped and in what quantities? Victory should be counted depending on which roles are alive. Most importantly, it must take observers into account.

**Comment by PUDGE133** [comment]
And yet I'm interested. With this configuration,
```yaml
endconditions:
    ChaosInsurgency:
        - Default 1:
            - ChaosInsurgency
            - ClassD
            - Tutorial
```
victory is counted differently each time. Either CI or class D.
What does this "Default 1" mean?
