### ISSUE TITLE
Your plugin gives out complete nonsense at the end of the round

### ISSUE THREAD

**Issue by PUDGE133** [BuildBoy12/EndConditions#3]
Your plugin gives out complete nonsense at the end of the round. The winning teams are those that shouldn't be winning at all. Either I'm dumb or your plugin is shit.
```yaml
#None of the following are case sensative, but it looks good
endconditions:
    # Name of the leading team
    FacilityForces:
        ##Condition name: Literally up to you, can be used as an identifier if you want
        ##The ONLY rule for this is to NOT have two with the same name that are under the same leading team.
        #Append "+science" or "+classd" to the name to check if at least one person has escaped from that team
        #Append "-science" or "-classd" to the name to check if nobody has escaped from that team
        #Note that this can create situations where the round will not end if there is one person alive. Make sure you cover all situations.
        - Default 1:
            #Who wins together, using ClassNames from #resources in the EXILED discord
            - NtfCommander
            - NtfLieutenant
            - NtfCadet
            - NtfScientist
            - FacilityGuard
            - Scientist
            - Tutorial
    ChaosInsurgency:
        - Default 1:
            - ChaosInsurgency
            - ClassD
            - Tutorial
    Anomalies:
        - Default 1:
            - Scp173
            - Scp106
            - Scp049
            - Scp079
            - Scp096
            - Scp0492
            - Scp93953
            - Scp93989
            - Tutorial
    Draw:
        - Default 1:
            - Spectator
            - Tutorial
```
There were 3 players. I used an instant explosion of the warhead. Judging by the logic of this config, the round should have ended in a draw. But for some reason MTF counted the victory.
